### ISSUE TITLE
Compiler Warning "extra qualification"

### ISSUE THREAD

**Issue by sughodke** [vdeconinck/QC3Control#7]
Building for Teensy causes the compilation to fail, it is strict about compiler warnings.

The fix is easy enough. Delete "QC3Control::" from line 215 of QCControl.h. 

```
-     void QC3Control::switchToContinuousMode();
+     void switchToContinuousMode();
```

https://github.com/vdeconinck/QC3Control/blob/master/src/QC3Control.h#L215

**Comment by vdeconinck** [comment]
Nice catch. I also have the issue now with another board. I think the Arduino IDE was made stricter regarding compiler warnings.
I just released v1.4.1 which includes your fix.
If it works, please this issue. If not, just add a comment
